import { BaseAdapter } from './base';
import type { AgentConfig, AgentConfigOptions } from '../types/agent';
export class AiderAdapter extends BaseAdapter {
  readonly id = 'aider';
  readonly displayName = 'Aider';
  protected detectionPaths() {
    return ['.aider.conf.yml'];
  }
  generateConfig(o: AgentConfigOptions): AgentConfig {
    return {
      agent: this.id,
      displayName: this.displayName,
      path: '.aider.conf.yml',
      format: 'yaml',
      content: `# Generated by @llmfaucet/sdk\nmodel: ${o.defaultModel}\nopenai-api-base: ${o.baseURL}\nopenai-api-key: ${o.apiKey}\n`,
      instructions: ['Restart Aider after writing this file.'],
    };
  }
}
