import { BaseAdapter } from './base';
import type { AgentConfig, AgentConfigOptions } from '../types/agent';
export class CodexAdapter extends BaseAdapter {
  readonly id = 'codex';
  readonly displayName = 'OpenAI Codex CLI';
  protected detectionPaths() {
    return ['.codex/config.toml'];
  }
  generateConfig(o: AgentConfigOptions): AgentConfig {
    return {
      agent: this.id,
      displayName: this.displayName,
      path: '.codex/config.toml',
      format: 'toml',
      content: `# Generated by @llmfaucet/sdk\nmodel = "${o.defaultModel}"\nbase_url = "${o.baseURL}"\napi_key = "${o.apiKey}"\n`,
      instructions: ['Use an environment variable for api_key in shared environments.'],
    };
  }
}
