import { Command } from 'commander';
import { detectAgents } from '../lib/detect';
import { isDedicatedConfigPath, readConfig, removeConfigFile } from '../lib/config-files';
import { output } from '../lib/output';

export const configCommand = new Command('config').description('Inspect generated agent configuration');
configCommand.command('show').action(async () => {
  const agents = await detectAgents();
  if (!agents.length) return output.info('No supported agent configuration found');
  for (const agent of agents) output.info(`${agent.displayName}: ${agent.path}`);
});
configCommand
  .command('reset')
  .option('--yes')
  .action(async (options: { yes?: boolean }) => {
    if (!options.yes) return output.warn('Pass --yes to remove llmfaucet configuration files');
    for (const agent of await detectAgents()) {
      if (!isDedicatedConfigPath(agent.path)) {
        output.info(`Skipped ${agent.path} (shared agent settings are never removed)`);
        continue;
      }
      const content = await readConfig(agent.path);
      if (!content?.toLowerCase().includes('llmfaucet')) {
        output.info(`Skipped ${agent.path} (not generated by llmfaucet)`);
        continue;
      }
      if (await removeConfigFile(agent.path)) output.success(`Removed ${agent.path}`);
      else output.info(`Skipped ${agent.path}`);
    }
  });
