import type { Env } from './types';
import { readSession } from './auth/sessions';

export const THEMES = ['system', 'light', 'dark'] as const;
export const MODEL_SELECTORS = ['auto', 'auto:fast', 'auto:smart', 'auto:coding'] as const;
export const WORKFLOWS = ['coding-agent', 'openai-app', 'automation', 'exploring-api'] as const;
type PreferenceInput = { theme?: string; defaultModelSelector?: string; primaryWorkflow?: string | null };
const allowedOrigin = (request: Request, env: Env): string | undefined => { const origin = request.headers.get('origin'); if (!origin) return undefined; const configured = [env.PUBLIC_BASE_URL, ...(env.PUBLIC_WEB_ORIGINS ?? '').split(',')].filter((value): value is string => Boolean(value)); return configured.some((value) => { try { return new URL(value).origin === origin; } catch { return false; } }) ? origin : undefined; };
const csrf = (request: Request, env: Env): boolean => { const origin = request.headers.get('origin'); return origin ? allowedOrigin(request, env) === origin : !env.PUBLIC_BASE_URL; };
const response = (request: Request, env: Env, data: unknown, status = 200) => { const origin = allowedOrigin(request, env); return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json', ...(origin ? { 'access-control-allow-origin': origin, 'access-control-allow-credentials': 'true', vary: 'Origin' } : {}) } }); };
const session = (request: Request, env: Env) => readSession(request, env);
export async function preferences(request: Request, env: Env): Promise<Response> { if (!env.DB) return response(request, env, { message: 'Preferences unavailable.' }, 503); const current = await session(request, env); if (!current) return response(request, env, { message: 'A valid account session is required.' }, 401); const row = await env.DB.prepare('SELECT p.theme, p.default_model_selector, p.primary_workflow, COALESCE(p.onboarding_completed_at, u.onboarding_completed_at) AS onboarding_completed_at, COALESCE(p.onboarding_dismissed_at, u.onboarding_dismissed_at) AS onboarding_dismissed_at, COALESCE(p.onboarding_version, u.onboarding_version) AS onboarding_version FROM users u LEFT JOIN user_preferences p ON p.user_id = u.id WHERE u.id = ?').bind(current.userId).first<Record<string, string | null>>(); return response(request, env, { preferences: { theme: row?.theme ?? 'system', defaultModelSelector: row?.default_model_selector ?? 'auto', primaryWorkflow: row?.primary_workflow ?? null, onboardingCompletedAt: row?.onboarding_completed_at ?? null, onboardingDismissedAt: row?.onboarding_dismissed_at ?? null, onboardingVersion: row?.onboarding_version ?? null } }); }
export async function updatePreferences(request: Request, env: Env): Promise<Response> { if (!env.DB) return response(request, env, { message: 'Preferences unavailable.' }, 503); const current = await session(request, env); if (!current) return response(request, env, { message: 'A valid account session is required.' }, 401); if (!csrf(request, env)) return response(request, env, { message: 'Origin validation failed.' }, 403); let body: PreferenceInput; try { body = await request.json() as PreferenceInput; } catch { return response(request, env, { message: 'Invalid JSON.' }, 400); } if (body.theme !== undefined && !(THEMES as readonly string[]).includes(body.theme)) return response(request, env, { message: 'Invalid theme.' }, 400); if (body.defaultModelSelector !== undefined && !(MODEL_SELECTORS as readonly string[]).includes(body.defaultModelSelector)) return response(request, env, { message: 'Invalid model selector.' }, 400); if (body.primaryWorkflow !== undefined && body.primaryWorkflow !== null && !(WORKFLOWS as readonly string[]).includes(body.primaryWorkflow)) return response(request, env, { message: 'Invalid workflow.' }, 400); const fields: string[] = []; const values: unknown[] = []; if (body.theme !== undefined) { fields.push('theme=?'); values.push(body.theme); } if (body.defaultModelSelector !== undefined) { fields.push('default_model_selector=?'); values.push(body.defaultModelSelector); } if (body.primaryWorkflow !== undefined) { fields.push('primary_workflow=?'); values.push(body.primaryWorkflow); } if (fields.length === 0) return preferences(request, env); const existing = await env.DB.prepare('SELECT user_id FROM user_preferences WHERE user_id=?').bind(current.userId).first(); if (!existing) await env.DB.prepare('INSERT INTO user_preferences (user_id) VALUES (?)').bind(current.userId).run(); await env.DB.prepare(`UPDATE user_preferences SET ${fields.join(', ')}, updated_at=CURRENT_TIMESTAMP WHERE user_id=?`).bind(...values, current.userId).run(); return preferences(request, env); }
export async function onboardingAction(request: Request, env: Env, action: 'complete' | 'dismiss' | 'replay'): Promise<Response> { if (!env.DB) return response(request, env, { message: 'Preferences unavailable.' }, 503); const current = await session(request, env); if (!current) return response(request, env, { message: 'A valid account session is required.' }, 401); if (!csrf(request, env)) return response(request, env, { message: 'Origin validation failed.' }, 403); const values = action === 'complete' ? ['onboarding_completed_at = CURRENT_TIMESTAMP', 'onboarding_dismissed_at = NULL', "onboarding_version = 'v1'"] : action === 'dismiss' ? ["onboarding_dismissed_at = CURRENT_TIMESTAMP", "onboarding_version = 'v1'"] : ['onboarding_completed_at = NULL', 'onboarding_dismissed_at = NULL', 'onboarding_version = NULL']; await env.DB.prepare('INSERT INTO user_preferences (user_id) VALUES (?) ON CONFLICT(user_id) DO NOTHING').bind(current.userId).run(); await env.DB.batch([env.DB.prepare(`UPDATE user_preferences SET ${values.join(', ')}, updated_at=CURRENT_TIMESTAMP WHERE user_id=?`).bind(current.userId), env.DB.prepare(`UPDATE users SET ${values.join(', ')}, updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(current.userId)]); return preferences(request, env); }
