name = "llmfaucet"
main = "src/index.ts"
compatibility_date = "2026-08-24"
workers_dev = true

[triggers]
crons = ["0 * * * *", "0 0 * * *"]

[vars]
ENVIRONMENT = "development"
CATALOG_URL = ""

[[kv_namespaces]]
binding = "BUDGETS"
id = "replace-with-dev-kv-id"

[[d1_databases]]
binding = "DB"
database_name = "llmfaucet-dev"
database_id = "replace-with-dev-d1-id"
[[queues.producers]]
binding = "QUEUE"
queue = "llmfaucet-queue-dev"
[[queues.consumers]]
queue = "llmfaucet-queue-dev"
max_batch_size = 10

[env.production]
name = "llmfaucet"
workers_dev = true
vars = { ENVIRONMENT = "production", CATALOG_URL = "" }
[[env.production.kv_namespaces]]
binding = "BUDGETS"
id = "9d5fca7879c445edba258aed07f3849f"
[[env.production.d1_databases]]
binding = "DB"
database_name = "llmfaucet-prod"
database_id = "97eabec5-22a7-4115-9461-bdd9ba51abcc"
[[env.production.queues.producers]]
binding = "QUEUE"
queue = "llmfaucet-queue-prod"
[[env.production.queues.consumers]]
queue = "llmfaucet-queue-prod"
max_batch_size = 10
[env.production.triggers]
crons = ["0 * * * *", "0 0 * * *"]

[env.preview]
name = "llmfaucet-preview"
workers_dev = true
vars = { ENVIRONMENT = "preview", CATALOG_URL = "" }
[[env.preview.kv_namespaces]]
binding = "BUDGETS"
id = "a6a725fd094b4080b5c4084283e9bde5"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "llmfaucet-preview"
database_id = "3fd26080-4b14-4b82-b555-8854ce8bbba4"
[[env.preview.queues.producers]]
binding = "QUEUE"
queue = "llmfaucet-queue-preview"
[[env.preview.queues.consumers]]
queue = "llmfaucet-queue-preview"
max_batch_size = 10
[env.preview.triggers]
crons = ["0 * * * *", "0 0 * * *"]
