CREATE TABLE IF NOT EXISTS budgets (key TEXT PRIMARY KEY, used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS tokens (token TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS request_logs (provider TEXT, model TEXT, status INTEGER NOT NULL, latency_ms INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS daily_stats (day TEXT PRIMARY KEY, requests INTEGER NOT NULL, failures INTEGER NOT NULL);
