'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { FlaskConical } from 'lucide-react';
import { api, isPreviewApiConfigured, previewApiEndpoint } from '@/lib/api-client';
import type { WaitlistApplication } from '@/lib/waitlist-types';
import { Button } from '@/components/ui/button';
import { CopyButton } from '@/components/copy-button';
import { EmptyState, ErrorState, LoadingState } from '@/components/data-states';

const previewBase = previewApiEndpoint;

export default function TesterPage() {
  const [application, setApplication] = useState<WaitlistApplication | null>(null); const [error, setError] = useState(''); const [key, setKey] = useState(''); const [busy, setBusy] = useState(false); const [loaded, setLoaded] = useState(false);
  useEffect(() => { api.waitlist().then(result => setApplication(result.application)).catch((e: Error) => setError(e.message)).finally(() => setLoaded(true)); }, []);
  async function createKey() { setBusy(true); try { const result = await api.createPreviewKey(); setKey(result.key); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (error) return <ErrorState message={error} />; if (!loaded) return <LoadingState label="Loading tester status" />;
  if (!application) return <div className="rounded-xl border border-border bg-card p-8"><FlaskConical className="size-7 text-emerald-500" /><h1 className="mt-5 text-3xl font-semibold">Help test llmfaucet</h1><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Apply for controlled preview access and help test coding-agent compatibility, routing quality, and fair-use behavior.</p><Button asChild className="mt-7"><Link href="/waitlist">Apply to test</Link></Button></div>;
  if (application.status === 'approved') return <div><p className="font-mono text-xs uppercase tracking-widest text-emerald-600">Early tester</p><h1 className="mt-3 text-3xl font-semibold">You’re an early tester</h1>{!isPreviewApiConfigured && <p className="mt-5 rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-800 dark:text-amber-200" role="alert">Preview access is approved, but this web environment is not configured for the preview Worker. Ask an operator to set NEXT_PUBLIC_API_BASE_URL to the preview API before creating a key.</p>}<div className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-border bg-card p-6"><p className="text-sm text-muted-foreground">Preview endpoint</p><code className="mt-3 block break-all text-sm">{previewBase}</code><CopyButton content={previewBase} className="mt-3" /><p className="mt-5 text-sm text-muted-foreground">Daily preview limit</p><p className="mt-1 text-xl font-semibold">100 requests</p><p className="mt-5 text-sm text-muted-foreground">Access ends</p><p className="mt-1 font-medium">{application.previewAccessExpiresAt ? new Date(application.previewAccessExpiresAt).toUTCString() : 'Not reported'}</p></div><div className="rounded-xl border border-border bg-card p-6"><h2 className="font-semibold">Preview key</h2>{key ? <div className="mt-4"><p className="text-xs text-muted-foreground">Copy this key now. It will not be shown again.</p><code className="mt-2 block break-all rounded bg-muted p-3 text-xs">{key}</code><CopyButton content={key} label="Copy preview key" /></div> : <><p className="mt-3 text-sm leading-6 text-muted-foreground">Create a preview key once you are ready. It is shown only once.</p><Button className="mt-5" onClick={() => void createKey()} disabled={busy || !isPreviewApiConfigured}>{busy ? 'Creating…' : 'Create preview key'}</Button></>}</div></div><div className="mt-6 rounded-xl border border-border bg-card p-6"><h2 className="font-semibold">Next steps</h2><ol className="mt-4 space-y-2 text-sm text-muted-foreground"><li>1. Configure your coding tool with the preview endpoint.</li><li>2. Run a real workflow and record the UTC timestamp.</li><li>3. Report sanitized issues in <a className="underline" href="https://github.com/llmfaucet/llmfaucet/discussions">GitHub Discussions</a>.</li></ol></div></div>;
  if (application.status === 'revoked' || application.status === 'rejected') return <EmptyState title="This application is no longer active" body="You can continue using the public endpoint with standard access." />;
  return <div className="rounded-xl border border-border bg-card p-8"><p className="font-mono text-xs uppercase tracking-widest text-emerald-600">{application.status === 'waitlisted' ? 'Waitlisted' : 'Pending review'}</p><h1 className="mt-4 text-3xl font-semibold">{application.status === 'waitlisted' ? 'You’re on the list' : 'Application received'}</h1><p className="mt-4 max-w-xl leading-7 text-muted-foreground">We review testers in small groups based on workflow fit, tool diversity, and feedback potential.</p><Button asChild variant="outline" className="mt-7"><Link href="/waitlist">View or edit application</Link></Button></div>;
}
