'use client';
import { useEffect, useState } from 'react';
import { Plus, ShieldAlert, Trash2 } from 'lucide-react';
import { api } from '@/lib/api-client';
import type { AccountResponse } from '@/lib/api-types';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { LoadingState, EmptyState, ErrorState } from '@/components/data-states';
import { CopyButton } from '@/components/copy-button';

export default function KeysPage() {
  const [keys, setKeys] = useState<AccountResponse['keys'] | null>(null); const [label, setLabel] = useState(''); const [created, setCreated] = useState<{ key: string; prefix: string } | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = () => api.keys().then(setKeys).catch((e: Error) => setError(e.message)); useEffect(() => { void load(); }, []);
  async function create() { setBusy(true); setError(''); try { const key = await api.createKey(label || 'default'); setCreated(key); setLabel(''); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function revoke(id: string) { if (!confirm('Revoke this key? Any apps using it will stop working.')) return; setError(''); try { await api.revokeKey(id); await load(); } catch (e) { setError((e as Error).message); } }
  return <div><div><p className="text-sm text-muted-foreground">Account</p><h1 className="mt-2 text-3xl font-semibold">API keys</h1><p className="mt-3 text-muted-foreground">Create named keys for your coding tools. Raw values cannot be recovered.</p></div>{error && <div className="mt-6"><ErrorState message={error} /></div>}<div className="mt-8 rounded-xl border border-border bg-card p-6"><h2 className="font-semibold">Create an API key</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="key-label">Key label</label><Input id="key-label" value={label} onChange={e => setLabel(e.target.value)} placeholder="codex-laptop" className="sm:max-w-sm" /><Button disabled={busy} onClick={() => void create()}><Plus className="mr-2 size-4" />{busy ? 'Creating…' : 'Create key'}</Button></div></div>{created && <div className="mt-4 rounded-xl border border-emerald-500/40 bg-emerald-500/5 p-6"><div className="flex gap-3"><ShieldAlert className="size-5 shrink-0 text-emerald-600" /><div><h2 className="font-semibold">Copy this key now. It cannot be shown again.</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><code className="rounded-md bg-background px-3 py-2 text-sm break-all">{created.key}</code><CopyButton value={created.key} label="Copy key" /></div></div></div></div>}{!keys ? <div className="mt-4"><LoadingState label="Loading keys" /></div> : keys.length === 0 ? <div className="mt-4"><EmptyState title="No API keys yet" body="Create your first named key to connect a client." /></div> : <div className="mt-4 overflow-hidden rounded-xl border border-border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-muted/40 text-muted-foreground"><tr><th scope="col" className="p-4">Label</th><th scope="col" className="p-4">Prefix</th><th scope="col" className="p-4">Status</th><th scope="col" className="p-4">Last used</th><th scope="col" className="p-4"><span className="sr-only">Actions</span></th></tr></thead><tbody>{keys.map(key => <tr className="border-t border-border" key={key.id}><td className="p-4 font-medium">{key.label}</td><td className="p-4 font-mono text-xs">{key.prefix}</td><td className="p-4 capitalize">{key.status}</td><td className="p-4 text-muted-foreground">{key.lastUsedAt ?? 'Never'}</td><td className="p-4 text-right"><Button variant="ghost" size="sm" onClick={() => void revoke(key.id)} disabled={key.status !== 'active'}><Trash2 className="mr-2 size-4" />Revoke</Button></td></tr>)}</tbody></table></div></div>}</div>;
}
