"use client"

import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Bot, BrainCircuit, Code2, FlaskConical, PlugZap, Route, Workflow, Wrench } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { CopyButton } from "@/components/copy-button"
import { PublicStats } from "@/components/public-stats"
import { GooeyTextReveal } from "@/components/ui/gooey-text-reveal"
import {
  ExpandableScreen,
  ExpandableScreenContent,
  ExpandableScreenTrigger,
} from "@/components/ui/expandable-screen"
import { ResearchBentoGrid } from "@/components/ui/research-bento-grid"
import { api } from "@/lib/api-client"

const baseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || "https://api.llmfaucet.dev"
const panes = [["init", "init", "min(92vw, 680px)"], ["gateway", "gateway.json", "620px"], ["early-testers", "early-testers/", "620px"]] as const
const installCommands = { bun: "bun add @llmfaucet/sdk", npm: "npm install @llmfaucet/sdk", pnpm: "pnpm add @llmfaucet/sdk", cli: "npx @llmfaucet/cli setup" } as const
const endpointCommand = `curl ${baseUrl}/v1/chat/completions`
const workflows = [["Cline", "https://github.com/cline.png?size=64"], ["Roo Code", "https://github.com/RooCodeInc.png?size=64"], ["Claude Code", "https://github.com/anthropics.png?size=64"], ["Codex CLI", "https://github.com/openai.png?size=64"], ["Aider", "https://github.com/Aider-AI.png?size=64"], ["Continue", "https://github.com/continuedev.png?size=64"]] as const
const bentoBrands = [{ name: "AI agents", icon: Bot }, { name: "MCP", icon: PlugZap }, { name: "Routing", icon: Route }, { name: "Code", icon: Code2 }, { name: "Models", icon: BrainCircuit }, { name: "Workflows", icon: Workflow }, { name: "Tools", icon: Wrench }] as const

function GroupHeader({ label, href, action = "View →" }: { label: string; href?: string; action?: string }) { return <div className="mb-3 flex min-w-0 items-center gap-3"><span className="shrink-0 font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground/70">{label}</span><span aria-hidden="true" className="h-px flex-1 bg-border" />{href && <Link href={href} className="shrink-0 font-mono text-[10px] uppercase tracking-[0.1em] text-emerald-600 hover:underline">{action}</Link>}</div> }
function VideoPlaceholder() { return <div className="relative flex aspect-video w-full items-center justify-center overflow-hidden rounded-lg border border-border bg-black"><Image src="/assets/banner.png" alt="llmfaucet video preview" fill sizes="(max-width: 768px) 92vw, 1200px" className="object-contain opacity-45" /><div className="absolute inset-0 grid place-items-center bg-black/35"><span className="border border-white/25 bg-black/70 px-4 py-2 font-mono text-[11px] uppercase tracking-[0.12em] text-white/80">Video preview coming soon</span></div></div> }
function WorkflowMark({ name, src }: { name: string; src: string }) { const [failed, setFailed] = useState(false); return failed ? <span aria-hidden="true" className="flex size-4 items-center justify-center rounded bg-muted text-[8px] font-bold text-muted-foreground">{name.replace(/[^A-Za-z]/g, '').slice(0, 2).toUpperCase()}</span> : <img src={src} alt="" aria-hidden="true" className="size-4 rounded object-contain" onError={() => setFailed(true)} /> }
function Pane({ index, title, width, active, children }: { index: number; title: string; width: string; active: boolean; children: React.ReactNode }) { return <section style={{ "--pane-w": width } as React.CSSProperties} data-active={active} className="group/landing-pane flex w-full shrink-0 snap-start scroll-mt-16 flex-col border-b md:h-full md:w-[var(--pane-w)] md:max-w-full md:overflow-hidden md:border-b-0 md:border-l md:first:border-l-0"><header className="flex h-8 shrink-0 items-center gap-2 border-b px-5 font-mono text-[11px] uppercase tracking-[0.08em] text-muted-foreground"><span aria-hidden="true" className="text-muted-foreground/40 group-data-[active=true]/landing-pane:text-emerald-500">{active ? "•" : "·"}</span><span>{title}</span><span className="ml-auto text-muted-foreground/40">{String(index + 1).padStart(2, "0")}</span></header><div className="flex min-h-0 flex-1 flex-col gap-5 overflow-y-auto overscroll-y-contain px-5 py-6 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden md:px-6">{children}</div></section> }

export function LandingRail() {
  const railRef = useRef<HTMLDivElement>(null)
  const [activeIndex, setActiveIndex] = useState(0)
  const [packageManager, setPackageManager] = useState<keyof typeof installCommands>("bun")
  const [sponsors, setSponsors] = useState<{ current: string[]; special: string[] } | null>(null)
  useEffect(() => {
    const rail = railRef.current
    if (!rail) return
    const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActiveIndex(Array.from(rail.children).indexOf(visible.target)) }, { root: rail, threshold: [0.55, 0.8] })
    Array.from(rail.children).forEach((pane) => observer.observe(pane))
    return () => observer.disconnect()
  }, [])
  useEffect(() => { api.publicSponsors().then((result) => setSponsors({ current: result.currentSponsors ?? result.sponsors, special: result.specialSponsors ?? [] })).catch(() => setSponsors(null)) }, [])
  const goTo = (index: number) => railRef.current?.children[index]?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "start" })
  return <div className="landing-rail flex h-full min-h-0 flex-col border-b"><div ref={railRef} role="group" aria-label="llmfaucet homepage sections" onWheel={(event) => { if (window.innerWidth >= 768 && Math.abs(event.deltaY) > Math.abs(event.deltaX)) { event.preventDefault(); event.currentTarget.scrollLeft += event.deltaY } }} className="flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-y-contain [scrollbar-width:none] [&::-webkit-scrollbar]:hidden md:flex-row md:overflow-x-auto md:overflow-y-hidden md:overscroll-x-contain [scroll-snap-type:x_mandatory]">
    <Pane index={0} title="init" width={panes[0][2]} active={activeIndex === 0}>
      <div className="flex flex-col gap-4"><div className="relative aspect-[2172/724] w-full overflow-hidden rounded-lg border border-border bg-black"><Image src="/assets/banner.png" alt="llmfaucet" fill priority sizes="(max-width: 768px) 92vw, 680px" className="object-contain" /></div><GooeyTextReveal mode="scroll" duration={1.4} stagger={0.12} blurAmount={0.4} className="max-w-xl"><p className="font-mono text-[15px] leading-[1.5] tracking-[-0.01em] text-muted-foreground">One endpoint for free AI models. Route apps and coding agents through a public OpenAI-compatible gateway with clear limits and health-aware fallbacks.</p></GooeyTextReveal></div>
      <span aria-hidden="true" className="h-px w-full bg-border" />
      <div><GroupHeader label="quickstart" href="/docs/quickstart" action="Read setup guide →" /><div className="flex flex-wrap items-center gap-x-5 gap-y-2 font-mono text-[13px]">{(Object.keys(installCommands) as Array<keyof typeof installCommands>).map((manager) => <button key={manager} type="button" aria-pressed={packageManager === manager} onClick={() => setPackageManager(manager)} className={`inline-flex items-center gap-2 py-1 transition-colors ${packageManager === manager ? "text-foreground" : "text-muted-foreground hover:text-foreground"}`}><InstallIcon name={manager} />{manager}</button>)}</div><div className="mt-4 flex items-start justify-between gap-4 border border-border bg-card px-4 py-3"><code className="min-w-0 overflow-x-auto font-mono text-[12px] leading-6 text-foreground">$ {installCommands[packageManager]}</code><CopyButton content={installCommands[packageManager]} label="Copy command" className="shrink-0" /></div><p className="mt-3 font-mono text-[12px] leading-5 text-muted-foreground">Install the SDK or configure the CLI, then point it at the llmfaucet endpoint.</p></div>
      <div><GroupHeader label="endpoint setup" href="/docs/quickstart" action="Read setup guide →" /><div className="flex items-start justify-between gap-4 border border-border bg-card px-4 py-3"><code className="min-w-0 overflow-x-auto font-mono text-[12px] leading-6 text-foreground">$ {endpointCommand}</code><CopyButton content={endpointCommand} label="Copy endpoint command" className="shrink-0" /></div><ExpandableScreen layoutId="landing-video" triggerRadius="12px" contentRadius="12px"><div className="mt-5 flex justify-center"><ExpandableScreenTrigger className="w-1/2 max-w-4xl"><VideoPlaceholder /></ExpandableScreenTrigger></div><ExpandableScreenContent className="bg-black"><div className="flex min-h-full w-full items-center justify-center p-4 sm:p-8"><div className="w-full max-w-6xl"><VideoPlaceholder /></div></div></ExpandableScreenContent></ExpandableScreen></div>
    </Pane>
    <Pane index={1} title="gateway.json" width={panes[1][2]} active={activeIndex === 1}>
      <div><GroupHeader label="how it works" /><div className="h-[clamp(320px,calc(100svh-420px),350px)] w-full overflow-hidden rounded-lg"><ResearchBentoGrid monthlyPrice={0} previousPrice={0} currency="USD" defaultSelectedBrand={0} brands={bentoBrands} copy={{ showcaseTitle: "One endpoint.", showcaseDescription: "Connect agents and apps through one compatible gateway.", pricingTitle: <>Routing setup.</>, pricingDescription: "Choose a selector and inspect its route.", pauseTitle: <>Gateway connection.</>, activeDescription: "Connected to healthy compatible sources.", pausedDescription: "Reconnect when a source becomes available." }} /></div></div>
      <div><GroupHeader label="workflows" href="/docs/agents" action="Open agent guides →" /><div className="grid grid-cols-2 gap-3 font-mono text-[12px] sm:grid-cols-3">{workflows.map(([name, icon]) => <div key={name} className="flex items-center gap-2 border border-border px-3 py-3"><WorkflowMark name={name} src={icon} /><span>{name}</span></div>)}</div></div>
      <div><GroupHeader label="fair use" href="/docs/limits" action="Read the limits guide →" /><div className="divide-y divide-border border-y border-border font-mono text-[12px]">{[["anonymous", "20 requests/day", "standard"], ["github account", "50 requests/day", "standard"], ["supporter", "200 requests/day", "priority"], ["pro", "500 requests/day", "high"]].map(([name, limit, priority]) => <div key={name} className="flex items-center justify-between gap-4 py-3"><span>{name}</span><span className="text-muted-foreground">{limit} · {priority}</span></div>)}</div></div>
    </Pane>
    <Pane index={2} title="early-testers/" width={panes[2][2]} active={activeIndex === 2}>
      <div><GroupHeader label="controlled preview" href="/waitlist" action="Apply to test →" /><div className="flex items-center gap-3"><FlaskConical className="size-5 shrink-0 text-emerald-500" aria-hidden="true" /><h2 className="text-2xl font-semibold tracking-tight">Help test the public AI gateway.</h2></div><p className="mt-3 font-mono text-[13px] leading-[1.6] text-muted-foreground">Join a small developer cohort testing coding-agent compatibility, routing quality, fair-use behavior, and provider reliability before wider release.</p><Button asChild className="mt-6"><Link href="/waitlist">Join early tester waitlist <ArrowRight className="ml-2 size-4" /></Link></Button></div>
      <div><GroupHeader label="github sponsors" href="https://github.com/sponsors/justinedevs" action="Support on GitHub →" /><h2 className="text-2xl font-semibold tracking-tight">Help keep the faucet flowing.</h2><p className="mt-3 font-mono text-[13px] leading-[1.6] text-muted-foreground">Sponsors help fund infrastructure, provider testing, documentation, and maintenance. Sponsorship provides higher fair-use limits and priority access—not guaranteed models or unlimited usage.</p></div>
      <div><GroupHeader label="sponsor directory" href="/sponsors" action="View all →" />{sponsors === null ? <p className="font-mono text-[13px] leading-[1.6] text-muted-foreground">Public sponsor data is unavailable right now.</p> : sponsors.current.length === 0 && sponsors.special.length === 0 ? <p className="font-mono text-[13px] leading-[1.6] text-muted-foreground">No active sponsors are reported yet.</p> : <div className="space-y-3">{sponsors.special.length > 0 && <div><p className="mb-2 font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground/70">special thanks</p><div className="flex flex-wrap gap-2">{sponsors.special.map((login) => <a key={login} href={`https://github.com/${encodeURIComponent(login)}`} className="border border-emerald-500/50 px-3 py-2 font-mono text-[12px] hover:border-foreground">@{login}</a>)}</div></div>}<div><p className="mb-2 font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground/70">current sponsors</p><div className="flex flex-wrap gap-2">{sponsors.current.slice(0, 8).map((login) => <a key={login} href={`https://github.com/${encodeURIComponent(login)}`} className="border border-border px-3 py-2 font-mono text-[12px] hover:border-foreground">@{login}</a>)}</div></div></div>}</div>
      <div><GroupHeader label="live public metrics" href="/status" action="View status →" /><PublicStats /></div>
    </Pane>
  </div><footer className="flex min-h-7 shrink-0 flex-wrap items-center gap-x-4 gap-y-1 border-t px-4 py-1.5 font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground"><span className="font-medium text-foreground"><span className="mr-1.5 text-emerald-500">•</span>llmfaucet</span><nav className="flex gap-3" aria-label="Landing sections">{panes.map(([id, label], index) => <button key={id} type="button" onClick={() => goTo(index)} aria-current={activeIndex === index ? "true" : undefined} className={activeIndex === index ? "text-foreground" : "hover:text-foreground"}>{index + 1}:{label}{activeIndex === index ? "*" : ""}</button>)}</nav><nav className="ml-auto flex gap-3" aria-label="Legal links"><Link href="/docs/limits">Policy</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/docs">Docs</Link></nav></footer></div>
}

function InstallIcon({ name }: { name: keyof typeof installCommands }) { if (name === "npm") return <span className="inline-flex size-4 items-center justify-center rounded-sm bg-red-600 text-[8px] font-bold text-white">npm</span>; if (name === "pnpm") return <span className="grid size-4 grid-cols-2 gap-px" aria-hidden="true">{Array.from({ length: 4 }, (_, index) => <span key={index} className={index === 3 ? "bg-white" : "bg-orange-400"} />)}</span>; if (name === "cli") return <span className="inline-flex size-4 items-center justify-center rounded-sm border border-current text-[9px] font-bold">$</span>; return <span className="inline-flex size-4 items-center justify-center rounded-full border-2 border-current text-[7px] font-bold">B</span> }
